### ISSUE TITLE
The app crashes on rotate

### ISSUE THREAD

**Issue by webmagnets** [algal/SelfSizingCellsDemo#3]
When the simulator or iPad is rotated the app crashes.

Any idea on how to fix this?

**Comment by algal** [comment]
I'm not seeing any crashes on Xcode6 6.3 and iOS SDK 8.3.

But I do see a mess of warnings about snapshotting views that have not been rendered. Since this demo includes no snapshotting code, I think this is an iOS bug.

Also, it's very kind of you to call this an "app"! :)
